name: Publish Library on Tag

on:
  push:
    tags:
      - 'v*'
permissions:
  contents: write
  packages: write
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
      - name: Import GPG Key
        uses: crazy-max/ghaction-import-gpg@v3
        with:
          gpg-private-key: ${{ secrets.SIGNING_KEY }}
          passphrase: ${{ secrets.SIGNING_PASSWORD }}
      - name: Extract version from tag
        uses: damienaicheh/extract-version-from-tag-action@v1.1.0
      - name: Extract Version from Tag
        run: |
          VERSION="$MAJOR.$MINOR.$PATCH"
          echo $VERSION
      - name: Build and Publish Library to Github Packages
        env:
          REGISTRY_URL: ${{ env.GHREGISTRY_URL }}
          LIBRARY_VERSION: $MAJOR.$MINOR.$PATCH
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          REGISTRY_USERNAME: ${{ github.actor }}
        run: ./gradlew publish -PLIBRARY_VERSION=${{ env.LIBRARY_VERSION }}
      - name: Build and Publish Library to Sonatype Repository
        env:
          REGISTRY_URL: ${{ env.OSSRH_URL }}
          LIBRARY_VERSION: $MAJOR.$MINOR.$PATCH
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          REGISTRY_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          REGISTRY_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        run: ./gradlew publish -PLIBRARY_VERSION=${{ env.LIBRARY_VERSION }}
      - uses: fregante/release-with-changelog@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-template: '- {title} ← {hash}'
          template: |
            ### Changelog
            
            {commits}
            
            {range}
            
            ❤
      - name: "✏️ Generate release changelog"
        uses: heinrichreimer/action-github-changelog-generator@v2.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          output: CHANGELOG.md
