name: Publish Library on Tag

on:
  push:
    tags:
      - 'v*'
permissions:
  contents: write
  packages: write
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
      - name: Import GPG Key
        uses: crazy-max/ghaction-import-gpg@v3
        with:
          gpg-private-key: ${{ secrets.SIGNING_KEY }}
          passphrase: ${{ secrets.SIGNING_PASSWORD }}
      - name: Extract Version from Tag
        run: echo "LIBRARY_VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
      - name: Build and Publish Kordinator Core Library
        env:
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}
          LIBRARY_VERSION: ${GITHUB_REF#refs/tags/v}
        run: ./gradlew publish -PLIBRARY_VERSION=${{ env.LIBRARY_VERSION }}
      - name: Build and Publish Kordinator Spring Boot 3 Library
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
        run: ./gradlew :libs:spring-kordinator:publish -PLIBRARY_VERSION=${{ env.LIBRARY_VERSION }}
      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LIBRARY_VERSION: ${GITHUB_REF#refs/tags/v}
        run: |
          LIBRARY_VERSION_EXPANDED="${LIBRARY_VERSION}"
          CHANGELOG_CONTENT=$(awk "/# \\[${LIBRARY_VERSION_EXPANDED}\\]/,/^# \\[/{print}" CHANGELOG.md)
          if [ -z "$CHANGELOG_CONTENT" ]; then
          CHANGELOG_CONTENT="No changelog for version $LIBRARY_VERSION_EXPANDED"
          fi
          gh release create "$LIBRARY_VERSION_EXPANDED" -F - <<< "$CHANGELOG_CONTENT"
