name: Publish Library on Tag

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
      - name: Extract version from tag
        id: get_version
        run: echo "LIBRARY_VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
      - name: Import GPG Key
        uses: crazy-max/ghaction-import-gpg@v3
        with:
          gpg-private-key: ${{ secrets.SIGNING_KEY }}
          passphrase: ${{ secrets.SIGNING_PASSWORD }}
      - name: Build and Publish Kordinator Core Library
        env:
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}
          LIBRARY_VERSION: ${{ steps.get_version.outputs.version }}
        run: ./gradlew publish
      - name: Build and Publish Kordinator Spring Boot 3 Library
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}
          LIBRARY_VERSION: ${{ steps.get_version.outputs.version }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
        run: ./gradlew publish
      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          CHANGELOG_CONTENT=$(awk '/# \['"$VERSION"'\]/,/^# \[/{print}' CHANGELOG.md)
          if [ -z "$CHANGELOG_CONTENT" ]; then
            CHANGELOG_CONTENT="No changelog for version $VERSION"
          fi
          gh release create $VERSION -F - <<< "$CHANGELOG_CONTENT"
